---
- src: https://github.com/ajanis/ansible-openldap.git
  name: openldap
- src: https://github.com/ajanis/ansible-nginx.git
  name: nginx
- src: https://github.com/ajanis/ansible-common.git
  name: common
- src: https://github.com/ajanis/ansible-docker.git
  name: docker
- src: https://github.com/ajanis/ansible-ceph-fs.git
  name: ceph-fs
- src: https://github.com/ajanis/ansible-mediaserver.git
  name: mediaserver
- src: https://github.com/ajanis/ansible-telegraf.git
  name: telegraf
- src: https://github.com/ajanis/ansible-influxdb.git
  name: influxdb
- src: https://github.com/ajanis/ansible-grafana.git
  name: grafana
- src: https://github.com/ajanis/ansible-nfs.git
  name: nfs